# Hands-On Pertemuan 10: Implementasi NoSQL Database - MongoDB

## Tujuan:
- Mengenal konsep dasar dan pengimplementasian database NoSQL, khususnya MongoDB.
- Melakukan berbagai operasi dasar pada MongoDB untuk analisis data.
- Mengasah keterampilan dalam menulis query yang lebih kompleks.

### 1. Menghubungkan ke Database MongoDB
- **Tugas 1**: Pastikan MongoDB telah terpasang dan berjalan. Hubungkan ke MongoDB lokal.

In [ ]:
from pymongo import MongoClient
# Inisialisasi client dan koneksi ke database
client = MongoClient('mongodb://localhost:27017/')
db = client['ByuDB']
collection = db['ByuTest']

# Contoh untuk memastikan koneksi
print('Connected to MongoDB')

### 2. Operasi CRUD Dasar
- **Tugas 2**: Insert, Update, dan Delete data pada koleksi `employees`.

In [ ]:
# Contoh Insert Data
employee_data = {
    'name': 'Alice',
    'department': 'Finance',
    'age': 29,
    'salary': 4500
}
collection.insert_one(employee_data)
print('Data inserted')

# Tugas: Insert beberapa data tambahan, lakukan update, serta delete data

In [ ]:
# Contoh Query Data
for employee in collection.find():
    print(employee)

In [ ]:
employee_data = [
    {
        'name': 'Bayu',
        'department': 'IT',
        'age': 19,
        'salary': 150000
    },
    {
        'name': 'Andi',
        'department': 'Finance',
        'age': 25,
        'salary': 200000
    },
    {
        'name': 'Siti',
        'department': 'Marketing',
        'age': 22,
        'salary': 180000
    },
    {
        'name': 'Beni',
        'department': 'Marketing',
        'age': 20,
        'salary': 180000
    },
    {
        'name': 'DIka',
        'department': 'IT',
        'age': 19,
        'salary': 180000
    },
    
]
    
result = collection.insert_many(employee_data)
print(f'Data inserted with IDs: {result.inserted_ids}')

# Menampilkan Data
for employee in collection.find():
    print(employee)

### 3. Query Lebih Kompleks Menggunakan Aggregation
- **Tugas 3**: Terapkan aggregation untuk menghitung rata-rata gaji per departemen.

In [ ]:
# Query Aggregation untuk mencari rata-rata gaji per departemen
pipeline = [
    {'$group': {'_id': '$department', 'average_salary': {'$avg': '$salary'}}}
]
for result in collection.aggregate(pipeline):
    print(result)

### 4. Latihan Tambahan
- **Latihan 4.1**: Buatlah koleksi baru `products` dan masukkan data produk (minimal 10 produk).
- **Latihan 4.2**: Lakukan query untuk menemukan produk dengan harga di atas rata-rata.
- **Latihan 4.3**: Buatlah aggregation pipeline untuk menghitung total produk dalam setiap kategori.

In [ ]:
from pymongo import MongoClient
# Inisialisasi client dan koneksi ke database
client = MongoClient('mongodb://localhost:27017/')
db = client['ByuDB']

# Pilih koleksi 'products'
products = db.products

# Contoh untuk memastikan koneksi
print('Connected to MongoDB')

# Daftar produk untuk dimasukkan

product_list = [

    {"nama": "Laptop", "harga": 9999000, "kategori": "Elektronik", "stok": 50},

    {"nama": "Ponsel Pintar", "harga": 4999000, "kategori": "Elektronik", "stok": 100},

    {"nama": "Headset", "harga": 799000, "kategori": "Elektronik", "stok": 200},

    {"nama": "Sepatu Lari", "harga": 899000, "kategori": "Olahraga", "stok": 75},

    {"nama": "Mesin Kopi", "harga": 599000, "kategori": "Peralatan Rumah", "stok": 30},

    {"nama": "Tas Ransel", "harga": 349000, "kategori": "Fashion", "stok": 150},

    {"nama": "Lampu Meja", "harga": 129000, "kategori": "Dekorasi Rumah", "stok": 80},

    {"nama": "Mouse Nirkabel", "harga": 199000, "kategori": "Elektronik", "stok": 120},

    {"nama": "Botol Minum", "harga": 59000, "kategori": "Olahraga", "stok": 200},

    {"nama": "Pot Tanaman", "harga": 39000, "kategori": "Dekorasi Rumah", "stok": 100},

    {"nama": "Matras Yoga", "harga": 179000, "kategori": "Olahraga", "stok": 60},

    {"nama": "Blender", "harga": 299000, "kategori": "Peralatan Rumah", "stok": 40}

]

# Masukkan produk ke dalam koleksi

result = products.insert_many(product_list)

# Verifikasi penyisipan

print(f"Berhasil memasukkan {len(result.inserted_ids)} dokumen")

# Tampilkan semua produk

for product in products.find():

    print(product)

# Tutup koneksi

client.close()

In [ ]:
from pymongo import MongoClient
from pprint import pprint

# Koneksi ke MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['ByuDB']
products = db.products

# Langkah 1: Menghitung rata-rata harga
average_price_pipeline = [
    {
        "$group": {
            "_id": None,
            "rata_rata_harga": {"$avg": "$harga"}
        }
    }
]

average_price_result = list(products.aggregate(average_price_pipeline))
average_price = average_price_result[0]['rata_rata_harga']

print(f"Rata-rata harga semua produk: Rp {average_price:,.0f}")

# Langkah 2: Query produk dengan harga di atas rata-rata
above_average_products = products.find({"harga": {"$gt": average_price}})

# Menampilkan hasil
print("\nProduk dengan harga di atas rata-rata:")
for product in above_average_products:
    print(f"\nNama: {product['nama']}")
    print(f"Kategori: {product['kategori']}")
    print(f"Harga: Rp {product['harga']:,.0f}")
    print(f"Stok: {product['stok']}")

# Menghitung jumlah produk di atas rata-rata
count_above_average = products.count_documents({"harga": {"$gt": average_price}})
print(f"\nJumlah produk di atas rata-rata harga: {count_above_average}")

# Tutup koneksi
client.close()

In [ ]:
from pymongo import MongoClient
from pprint import pprint

# Koneksi ke MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['ByuDB']
products = db.products

# Aggregation pipeline untuk menghitung total produk per kategori
pipeline = [
    {
        "$group": {
            "_id": "$kategori",
            "total_produk": {"$sum": 1},
            "total_stok": {"$sum": "$stok"},
            "rata_rata_harga": {"$avg": "$harga"}
        }
    },
    {
        "$sort": {"total_produk": -1}
    }
]

# Jalankan agregasi
result = list(products.aggregate(pipeline))

# Tampilkan hasil
print("Total Produk per Kategori:")
for category in result:
    print(f"\nKategori: {category['_id']}")
    print(f"Total Produk: {category['total_produk']}")
    print(f"Total Stok: {category['total_stok']}")
    print(f"Rata-rata Harga: Rp {category['rata_rata_harga']:,.0f}")

# Tutup koneksi
client.close()

### 5. Tugas
- **Tugas 1**: Cari 5 karyawan dengan gaji tertinggi dalam setiap departemen, gunakan query atau aggregation yang sesuai.
- **Tugas 2**: Buatlah skenario di mana Anda harus menghapus karyawan yang berusia di bawah 25 tahun dari database.
- **Tugas 3**: Buatlah laporan ringkas (menggunakan MongoDB query) yang menghitung total gaji karyawan di setiap departemen, serta rata-rata umur karyawan.

In [ ]:
from pymongo import MongoClient
from pprint import pprint

# Koneksi ke MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['ByuDB']  
collection = db.ByuTest  

# Aggregation pipeline
pipeline = [
    # Kelompokkan berdasarkan departemen
    {
        "$group": {
            "_id": "$department",
            "karyawan": {
                "$push": {
                    "name": "$name",
                    "salary": "$salary",
                    "age": "$age"
                }
            }
        }
    },
    # Urutkan karyawan dalam setiap departemen berdasarkan gaji (descending)
    {
        "$project": {
            "karyawan": {
                "$sortArray": {
                    "input": "$karyawan",
                    "sortBy": {"salary": -1}
                }
            }
        }
    },
    # Ambil 5 karyawan teratas dari setiap departemen
    {
        "$project": {
            "karyawan": {"$slice": ["$karyawan", 5]}
        }
    },
    # Urutkan hasil berdasarkan nama departemen
    {
        "$sort": {"_id": 1}
    }
]

# Jalankan aggregation
result = collection.aggregate(pipeline)

# Tampilkan hasil
for dept in result:
    print(f"\nDepartemen: {dept['_id']}")
    print("Top 5 Karyawan dengan Gaji Tertinggi:")
    for i, kary in enumerate(dept['karyawan'], 1):
        print(f"  {i}. Nama: {kary['name']}")
        print(f"     Umur: {kary['age']} tahun")
        print(f"     Gaji: Rp {kary['salary']:,.0f}")

# Tutup koneksi
client.close()

In [ ]:
from pymongo import MongoClient
from pprint import pprint

# Koneksi ke MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['ByuDB']  
collection = db.ByuTest  
# Aggregation pipeline
pipeline = [
    # Kelompokkan berdasarkan departemen
    {
        "$group": {
            "_id": "$department",
            "total_gaji": {"$sum": "$salary"},
            "jumlah_karyawan": {"$sum": 1},
            "total_umur": {"$sum": "$age"}
        }
    },
    # Hitung rata-rata umur
    {
        "$project": {
            "department": "$_id",
            "total_gaji": 1,
            "jumlah_karyawan": 1,
            "rata_rata_umur": {"$divide": ["$total_umur", "$jumlah_karyawan"]}
        }
    },
    # Urutkan hasil berdasarkan nama departemen
    {
        "$sort": {"department": 1}
    }
]

# Jalankan aggregation
result = collection.aggregate(pipeline)

# Tampilkan hasil
print("Laporan Ringkas Departemen:")
print("===========================")
for dept in result:
    print(f"\nDepartemen: {dept['department']}")
    print(f"Total Gaji: Rp {dept['total_gaji']:,.0f}")
    print(f"Jumlah Karyawan: {dept['jumlah_karyawan']}")
    print(f"Rata-rata Umur: {dept['rata_rata_umur']:.2f} tahun")

# Tutup koneksi
client.close()

In [ ]:
from pymongo import MongoClient

# Koneksi ke MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['perusahaan']
collection = db.ByuTest

# Dapatkan jumlah karyawan sebelum penghapusan
jumlah_sebelum = collection.count_documents({})

# Cari karyawan yang berusia di bawah 25 tahun
karyawan_muda = collection.find({"age": {"$lt": 25}})

# Simpan informasi karyawan yang akan dihapus (opsional)
karyawan_dihapus = list(karyawan_muda)

# Hapus karyawan yang berusia di bawah 25 tahun
hasil = collection.delete_many({"age": {"$lt": 25}})

# Dapatkan jumlah karyawan setelah penghapusan
jumlah_setelah = collection.count_documents({})

# Tampilkan hasil
print(f"Jumlah karyawan sebelum penghapusan: {jumlah_sebelum}")
print(f"Jumlah karyawan yang dihapus: {hasil.deleted_count}")
print(f"Jumlah karyawan setelah penghapusan: {jumlah_setelah}")

print("\nDaftar karyawan yang dihapus:")
for k in karyawan_dihapus:
    print(f"Nama: {k.get('name', 'N/A')}, Usia: {k.get('age', 'N/A')}, Departemen: {k.get('department', 'N/A')}")

# Tutup koneksi
client.close()